# Site settings
source: src
title: Bits and pieces
email: kbourn@gmail.com
description: "Misc notes"
highlighter: pygments
markdown: redcarpet
baseurl: "/"
encoding: "utf-8"
url: "http://bkon.github.io"
twitter_username: bkonst
github_username: bkon
disqus_username: bkongithub
linkedin_username: konstantin-burnaev
isso_domain: false
paginate: 5
exclude:
  - sass
  - jsx

# Permalinks
permalink:        pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
